export const RISK_CONSTANTS = {
  MAX_OPEN_POSITIONS: 5,
  MAX_ORDERS_PER_HOUR: 10,
  MIN_POSITION_SIZE_PCT: 2.0,
  MAX_POSITION_SIZE_PCT: 5.0,
  STOP_LOSS_PCT: -2.0,
  TAKE_PROFIT_PCT: 4.0,
  MAX_DAILY_DRAWDOWN_PCT: 3.0,
  STALENESS_LIMIT_MS: 1500,
  RECONCILIATION_INTERVAL_MS: 15_000,
  KILL_SWITCH_DEADLINE_MS: 500,
  ORDER_TIMEOUT_MS: 5_000,
  TIME_SYNC_INTERVAL_MS: 30_000,
  DISCREPANCY_TOLERANCE_USD: 1.0,
  MTF_TIMEFRAMES: ['m15', 'h1', 'h4', 'd1'] as const,
  SYMBOL_COOLDOWN_MS: 60 * 60_000,
  MAX_REENTRY_PER_SYMBOL_PER_DAY: 3,
  SYMBOL_COOLDOWN_WINDOW_MS: 24 * 60 * 60_000,
} as const;

export const SPOT_ONLY_SCOPES = ['spot'] as const;
export const FORBIDDEN_KEY_SCOPES = ['withdrawal', 'withdraw', 'margin', 'transfer', 'futures', 'leverage'] as const;
